### ISSUE TITLE
Question on required videos

### ISSUE THREAD

**Issue by hwjiang1510** [epic-kitchens/VISOR-FrameExtraction#1]
Hi, thanks for the great work!

I have some questions regarding the required videos in `videos_path`. I saw in the GroundTruth-SparseAnnotations, the annotations and sparse frames are provided from participant-01 to participant-37. However, EPIC-KITCHENS-100 videos only covered a part of the participants, for example, there is no participant-08 in EPIC-KITCHENS-100.

Could you give more instructions on which video dataset is required for VISOR?

**Comment by hwjiang1510** [comment]
Figured out the problem. VISOR is not built on Epic-Kitchens-100, but it is built on the full Epic-Kitchen dataset. You should use the download script to download videos collected from all participants.

**Comment by dimadamen** [comment]
You seem to have a misunderstanding of what EPIC-KITCHENS-100 is. It is made up of the first set of 55 hour videos, and an extended set of 45 hours video. Together they form "EPIC-KITCHENS-100", so there's nothing called full dataset.
You need to download both sets of videos to be evaluating on EPIC-KITCHENS-100. 
VISOR uses videos from this dataset.
