### ISSUE TITLE
Problem for extraction

### ISSUE THREAD

**Issue by hwjiang1510** [epic-kitchens/VISOR-FrameExtraction#2]
Hi, I noticed that there are some random prefix in some of the interpolation data.

For example, `Interpolations-DenseAnnotations/train/P22_117_interpolation.json` has some image name with the prefix `0032`, e.g. `0032_P22_117_frame_0000017726.png`. These images cannot match any in GroundTruth-SparseAnnotations/rgb_frames/train/P22/P22_117, and it makes the extraction failed. It is the same with `P37_103_interpolations.json`, where some image names have the prefix `0061`.

Could you check the interpolation.json files and clean the data?

**Comment by AhmadDarKhalil** [comment]
Thank you for raising the issue, any image name with a prefix like this should be ignored and added by mistake. We will publish a script to clean all of these cases.

**Comment by AhmadDarKhalil** [comment]
Sorry for a long time before getting back to the issue! we've already resolved the problem by providing a correction script "correct_interpolations.py", please read the instructions in the repository for more information on how to use the script to get the data clean and ready to use.
Thanks a lot for being patient and we really hope you'll enjoy using VISOR!
