### ISSUE TITLE
In_contact for dense annotations

### ISSUE THREAD

**Issue by Davidyao99** [epic-kitchens/VISOR-FrameExtraction#5]
For the sparse annotations, we have labels for in_contact_object. I was wondering if this label is propagated during interpolation to dense annotations. Thank you!

**Comment by AhmadDarKhalil** [comment]
Thank you for your question,
We did the sparse annotations' flags manually.  The flags cannot be interpolated as the objects can go in or out of contact at any point during the interpolations.

**Comment by Davidyao99** [comment]
That makes sense. Thank you!!
