### ISSUE TITLE
Obtaining interpolated segmentations

### ISSUE THREAD

**Issue by dusangrujicic** [epic-kitchens/VISOR-FrameExtraction#6]
How are interpolated segmentation masks obtained? There does seem to exist code for extracting the RGB frames needed in the interpolation step, but I haven't found any code that uses the interpolation jsons to create dense segmentations.

**Comment by dimadamen** [comment]
This repo is to allow you to extract the frames. 
The code that uses interpolation sons to visualise dense segmentations is in another repo: https://github.com/epic-kitchens/VISOR-VIS

We have not released the exact code for obtaining the dense interpolations from sparse segmentations (thought not sure this is your Q) but this is based on our VOS models and code https://github.com/epic-kitchens/VISOR-VOS - the same models was used to create the dense interpolations.
Please refer to our paper Section 3.4 and Appendix G for how the segmentations were obtained. The section describes how the interpolated segmentations were obtained.
